# Generated by Django 6.1.1 on 2026-09-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storesettings_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storesettings',
            old_name='descrition',
            new_name='description',
        ),
    ]
