# Generated by Django 6.1.1 on 2026-09-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_descrition_storesettings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
